### PR TITLE
Fix the error while running do_package()

### PR DESCRIPTION
**Pull request by joone**
Add the following to chromium_58.0.3029.110.bb.bb
INHIBIT_PACKAGE_DEBUG_SPLIT = "1"
INSANE_SKIP_${PN} += "already-stripped"

### CODE REVIEW

**Comment by rakuco** [comment]
What error are you having if you omit those 2 lines? Everything works fine here, even though packaging does take a long time.

**Comment by rakuco** [comment]
> What error are you having if you omit those 2 lines?

OK, I'm assuming it's the error message that was removed in https://github.com/joone/wiki/commit/e1760498477b5a7fb9c2f2dd0fe8f6a1ad4afa25 (the "chromium-bin" is already stripped messages).

This problem should have been solved by https://github.com/rakuco/meta-crosswalk/commit/5aae1539c3d62b295dba40f494397c0797140b0f, but looking at it again it was just hiding the problem at the time. The issue here is that even if we remove `-g` from the build flags like that commit is doing we still end up with fairly big (>4Gb) `chrome` binaries -- too big in 32-bit installations for utilities like `readelf` or `file` to properly parse them. Since `package.bb` just calls `file` to determine if an executable has been stripped or not (by grepping for "not stripped" in `file`'s output) and `file` does not work with such huge binaries on i586 and produces bogus output that says the file has already been stripped when it has not.

At the time I made that commit in M54, the generated binary was around 4.2G in size, which caused `file` to at least not wrongly report the binary had already been stripped. The M58 binary is around 4.9G in size, and makes the problem come back again.

I'm still waiting for an M58 i586 build with your patch to finish here, but my guess is that it will not strip anything at all, meaning the Chromium package will be very big.

I think what we need here is to set `INSANE_SKIP_${PN} += "already-stripped"` and `INHIBIT_PACKAGE_DEBUG_SPLIT` if we do the stripping ourselves during the build. I'll continue checking this tomorrow.

**Comment by joone** [comment]
I've updated the patch.

**Comment by rakuco** [comment]
This still needs some work. As far as I can see, just `INHIBIT_PACKAGE_DEBUG_SPLIT` + `INSANE_SKIP` will only prevent debug symbols from being extracted + prevent Yocto from erroneously complaining that the `chrome` binary has already been stripped.

Another problem I've noticed is that `is_official_build=true` causes the `symbols` GN variable to default to 2, meaning even if you have not set `DEBUG_BUILD_pn-chromium="1"` in your `local.conf` the build will still pass `-g2` to the compiler in addition to your build flags. In fact, if `DEBUG_BUILD` is not set we end up with something like `-g2 -O2 -pipe` which generates an even bigger binary.

I hope to have more time to continue checking this issue this week.

**Comment by rakuco** [comment]
Right; we've chatted a bit about this, but to summarize it publicly: please try my "debug-flags-32-bits" branch, it should have a commit that solves the problem by preventing GN from adding -g2 automatically, while also using -g1 instead of -g in `DEBUG_FLAGS` on 32-bit target architectures.

**Comment by rakuco** [comment]
ping

**Comment by rakuco** [comment]
I've merged that branch, it's easier to just revert the commit if necessary.

**Pull request closed without merging**
