### PR TITLE
Fix typo in webrtc build config

### PR DESCRIPTION
**Pull request by joone**

### CODE REVIEW

**Comment by rakuco** [comment]
The actual webrtc change looks fine, but it seems like you pushed some additional, unrelated commits to your branch.

**Comment by joone** [comment]
ok, I will fix it.

**Comment by rakuco** [comment]
Also note that Chromium 59 was finally moved to the stable channel, and I've pushed an updated recipe to the chromium59 branch (WebRTC support had to be made mandatory for the time being there due to https://bugs.chromium.org/p/chromium/issues/detail?id=730019)

**Comment by rakuco** [comment]
> but it seems like you pushed some additional, unrelated commits to your branch.

The actual WebRTC bug has since been fixed, and this branch is still being used for unrelated changes. Closing for now, as it looks like they are not yet ready for prime-time.

**Pull request closed without merging**
